changelog:
  authors:
    - sigma
  categories:
    - title: New Features
      labels:
        - "enhancement"
    - title: Bug Fix
      labels:
        - "bug"
    - title: Other Changes
      labels:
        - "*"
