services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
      # cache_from:
      #   - ref=ghcr.io/ryosukedtomita/devsecops-demo-aws-ecs,type=registry,mode=max
      # cache_to:
      #   - ref=ghcr.io/ryosukedtomita/devsecops-demo-aws-ecs,type=registry,mode=max
    image: react-app:latest
    container_name: react-app-container
    ports:
      - 80:8080 # localport:dockerport
