services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
      # cache_from:
      #   - ghcr.io/ryosukedtomita/devsecops-demo-aws-ecs
      #   - type=inline
      # cache_to:
      #   - ghcr.io/ryosukedtomita/devsecops-demo-aws-ecs
      #   - type=inline
    image: react-app:latest
    container_name: react-app-container
    ports:
      - 80:8080 # localport:dockerport
