version: '3'

services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: react-app:latest
    container_name: react-app-container
    ports:
      - 80:8080 # localport:dockerport
