name: github-comment
on: [push]

defaults:
  run:
    shell: bash

jobs:
  github-comment-test: # job id(Typed by user)
    runs-on: ubuntu-latest

    steps:
      # Checkout repository to runner
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: install package using aqua
        uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.29.0

      - run: github-comment post -k hello --token ${{ secrets.TOKEN }}
      - name: exit=0 then no comment
        run: github-comment exec --token ${{ secrets.TOKEN }} -- ls
      - name: exit!=0 then comment
        run: github-comment exec --token ${{ secrets.TOKEN }} -- ls /not_exist
