name: actions-lint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml

defaults:
  run:
    shell: bash

jobs:
  run-ghalint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: clone application source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: install package using aqua
        uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.29.0

      - name: run ghalint
        run: github-comment exec --token ${{ secrets.token }} -- ghalint run
