name: run-jest
on: [push]

defaults:
  run:
    shell: bash

jobs:
  frontend-jest: # job id(Typed by user)
    runs-on: ubuntu-latest

    steps:
      # Checkout repository to runner
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up node20
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: cd /home/runner/work/devsecops-demo-aws-ecs/devsecops-demo-aws-ecs && npm install

      - name: Run npm test
        run: cd /home/runner/work/devsecops-demo-aws-ecs/devsecops-demo-aws-ecs && npm test -- --watchAll=false
