name: run-jest
on:
  push:
    paths:
      - "src/**.tsx"
      - "src/**.ts"
      - "public/**.html"
      - ".github/workflows/react-jest.yaml"
defaults:
  run:
    shell: bash

jobs:
  frontend-jest: # job id(typed by user)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      # デフォルトのワーキングディレクトリのため設定不要だが，明示的に指定。
      run:
        working-directory: /home/runner/work/devsecops-demo-aws-ecs/devsecops-demo-aws-ecs


    steps:
      # checkout repository to runner
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: set up node20
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '20'

      - name: install package using aqua
        uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.29.0

      - name: install dependencies
        run: github-comment exec --token ${{ secrets.token }} --  npm install

      - name: run npm test
        run: github-comment exec --token ${{ secrets.token }} -- npm test -- --watchall=false
