name: Create a zip in Releases when a tag is created.
on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

env:
  ZIP_FILE: tool_doc.zip

jobs:
  create_published:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: clone application source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: create zip
        run: zip -r ${{ env.ZIP_FILE }} doc

      - name: upload Releases
        uses: shogo82148/actions-upload-release-asset@8f032eff0255912cc9c8455797fd6d72f25c7ab7 # v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ZIP_FILE }}
          asset_name: ${{ env.ZIP_FILE }}
